# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: <%= ENV.fetch("DATABASE_TIMEOUT") { 5000 } %>

development:
  <<: *default
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_DATABASE_HOST"] %>
  database: <%= ENV["DATABASE_DATABASE_NAME"] %>

test:
  <<: *default
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_DATABASE_HOST"] %>
  database: DATABASE_admin_test

staging:
  <<: *default
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_DATABASE_HOST"] %>
  database: <%= ENV["DATABASE_DATABASE_NAME"] %>

production:
  <<: *default
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_DATABASE_HOST"] %>
  database: <%= ENV["DATABASE_DATABASE_NAME"] %>
